-- Audit columns on every `core` table (issue #516; owner rule, Антон,
-- 2026-09-22; ADR-004 amendment A2).
--
-- `created_at`, `created_by`, `updated_at`, `updated_by` are mandatory on every
-- platform table BY DEFAULT. They do not replace the append-only journal
-- `core.audit_event` (spec `docs/specs/201-universal-edit-audit.md`): the
-- journal is the diff HISTORY, these four are the row's own current facts —
-- «when and by whom was this created / last changed» — which every screen and
-- every query asks without joining the journal. The pain that produced the
-- rule: the finance intake item had no submission timestamp at all, so the
-- owner could not see when a request was filed (#517).
--
-- The `ALTER TABLE … ADD COLUMN` block at the top is GENERATED by drizzle-kit
-- (so the snapshot under `meta/` knows about the columns); everything below it
-- is HAND-WRITTEN, because drizzle-orm 0.45 can express neither a PL/pgSQL
-- function, nor a trigger, nor a data backfill — the same shape
-- `0003_universal_edit_audit.sql` established here.
--
-- Order: generated columns -> the FKs to `core.member` -> the capture
-- function's one-line amendment -> the stamping function -> the stamping
-- triggers -> the re-attached capture triggers (their whitelists gain the two
-- immutable audit columns) -> the journal-backed backfill LAST, with user
-- triggers off.
--

ALTER TABLE "core"."finance_account" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_account" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_account" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_account" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_category" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_category" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_category" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_category" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_conversion_step" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_conversion_step" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_conversion_step" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_conversion_step" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_counterparty" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_counterparty" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_currency" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_currency" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_currency" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_currency" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_document_link" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_document_link" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_document_link" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_document_link" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_document" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_document" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_document" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_document" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_intake_item" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_intake_item" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_intake_item" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_operation" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_operation" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_operation" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_operation" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_posting" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_posting" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_posting" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_posting" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_product" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_product" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_product" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_product" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_project" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_project" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_project" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_project" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_purpose_proposal" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_purpose_proposal" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_purpose_proposal" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_purpose" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_purpose" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."finance_purpose" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."finance_purpose" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_assessment" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_assessment" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_assessment" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_assessment" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_participant" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_participant" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_participant" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_participant" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_period" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_period" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_period" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_period" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_publication_message" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_publication_message" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_publication_message" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_publication_message" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_publication" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_publication" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."hours_publication" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."hours_publication" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."member_alias" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."member_alias" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."member_alias" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "core"."member_alias" ADD COLUMN "updated_by" integer;--> statement-breakpoint
ALTER TABLE "core"."member" ADD COLUMN "created_by" integer;--> statement-breakpoint
ALTER TABLE "core"."member" ADD COLUMN "updated_by" integer;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 1. `created_by` / `updated_by` are `core.member(id)` — the FKs, by hand
-- ---------------------------------------------------------------------------
--
-- Written here rather than declared in the schema files, because a drizzle
-- `.references(() => member.id)` in `schema/finance/` or `schema/hours/` would
-- import `schema/member/` into another module's schema directory — the import
-- ADR-004 §6 keeps out of a module. Same shape as
-- `finance_intake_item.created_by` and `finance_posting.member_id` (spec 338
-- EARS-322) already carry.
--
-- `ON DELETE SET NULL`: a member row disappearing must not take an invoice, a
-- ledger posting or a request with it. The attribution degrades to «nobody we
-- still have», which is the honest reading, and the JOURNAL still holds that
-- write's actor email — the two records are complementary, not redundant.
--
-- Catalog-driven and skip-if-present rather than 42 literal statements: two of
-- these columns (`finance_counterparty.created_by`,
-- `finance_intake_item.created_by`) already carry a FK from `0009`,
-- `ADD CONSTRAINT` has no `IF NOT EXISTS`, and a NOT NULL column cannot take
-- `ON DELETE SET NULL` at all.

DO $audit_columns_fk$
DECLARE
	rec record;
BEGIN
	FOR rec IN
		SELECT cls.relname AS table_name, att.attname AS column_name, att.attnotnull AS is_not_null
		FROM pg_class cls
		JOIN pg_namespace nsp ON nsp.oid = cls.relnamespace
		JOIN pg_attribute att ON att.attrelid = cls.oid
		WHERE nsp.nspname = 'core'
			AND cls.relkind = 'r'
			AND att.attname IN ('created_by', 'updated_by')
			AND att.attnum > 0
			AND NOT att.attisdropped
			AND NOT EXISTS (
				SELECT 1 FROM pg_constraint con
				WHERE con.conrelid = cls.oid
					AND con.contype = 'f'
					AND att.attnum = ANY (con.conkey)
			)
		ORDER BY cls.relname, att.attname
	LOOP
		EXECUTE format(
			'ALTER TABLE core.%I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES core.member(id) ON DELETE %s',
			rec.table_name,
			rec.table_name || '_' || rec.column_name || '_member_fk',
			rec.column_name,
			-- A NOT NULL column cannot be nulled by a cascade; it keeps the
			-- default NO ACTION, which is the only truthful option there.
			CASE WHEN rec.is_not_null THEN 'NO ACTION' ELSE 'SET NULL' END
		);
	END LOOP;
END
$audit_columns_fk$;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 2. The capture function gains ONE line (spec 201 EARS-2, EARS-3)
-- ---------------------------------------------------------------------------
--
-- Re-emitted whole, because `CREATE OR REPLACE FUNCTION` is how PL/pgSQL is
-- amended; the only difference from `0003_universal_edit_audit.sql` is the
-- bookkeeping skip, which now covers `updated_by` beside `updated_at`. The
-- comment at that line carries the reason.

CREATE OR REPLACE FUNCTION "core"."audit_row_change"() RETURNS trigger
	LANGUAGE plpgsql
	SECURITY DEFINER
	SET search_path = pg_catalog, core
AS $$
DECLARE
	whitelist   text[] := TG_ARGV;
	old_row     jsonb;
	new_row     jsonb;
	row_diff    jsonb := '{}'::jsonb;
	column_name text;
	old_value   jsonb;
	new_value   jsonb;
	pk_value    jsonb;
	actor       text;
	src         text;
	app_marked  boolean;
BEGIN
	-- --- attribution (EARS-6, EARS-7, EARS-8, EARS-26) ---------------------
	--
	-- `current_setting(name, true)` — the TWO-argument form, which returns NULL
	-- for an unset GUC instead of erroring, so the refusal below is OUR message
	-- and not Postgres's «unrecognized configuration parameter».
	actor      := nullif(current_setting('app.actor_email', true), '');
	src        := nullif(current_setting('app.source', true), '');
	app_marked := nullif(current_setting('app.connection', true), '') = 'app';

	IF src IS NULL THEN
		-- No context. WHOSE connection is it? The application's pool marks every
		-- socket it opens (`-c app.connection=app`, src/lib/platform/db/client.ts);
		-- a psql session, the drizzle-kit migration runner and a restore do not.
		IF app_marked THEN
			RAISE EXCEPTION
				'audit: actor context not set for %.% — an application write must run through platformTransaction(ctx, …), which issues set_config(''app.actor_email'', …, true) and set_config(''app.source'', …, true) inside the transaction (spec 201 EARS-24, EARS-26)',
				TG_TABLE_SCHEMA, TG_TABLE_NAME;
		END IF;
		-- Unmarked connection: somebody worked on the database directly. Append
		-- the row, degrade the attribution, never fabricate an actor (EARS-8).
		src   := 'db-direct';
		actor := NULL;
	ELSE
		-- The closed set of EARS-7. `db-direct` is the trigger's OWN fallback and
		-- is not a value any caller may set — letting an app write borrow it would
		-- make the ledger lie about the door the change came through.
		IF src !~ '^(portal|migration|manual-dba|system:[a-z0-9][a-z0-9._-]*|cli:[a-z0-9][a-z0-9._-]*)$' THEN
			RAISE EXCEPTION
				'audit: app.source «%» is not in the closed set portal | system:<job> | cli:<name> | migration | manual-dba (spec 201 EARS-7); db-direct is the trigger''s own fallback and cannot be set by a caller',
				src;
		END IF;
		-- The actor is required only where a human exists (EARS-7, EARS-9).
		IF src = 'portal' AND actor IS NULL THEN
			RAISE EXCEPTION
				'audit: app.source = ''portal'' means an authenticated request, so app.actor_email must be set (spec 201 EARS-7, EARS-9)';
		END IF;
	END IF;

	-- --- the diff (EARS-2, EARS-3, EARS-16, EARS-27) -----------------------
	IF TG_OP = 'INSERT' THEN
		new_row := to_jsonb(NEW);
	ELSIF TG_OP = 'DELETE' THEN
		old_row := to_jsonb(OLD);
	ELSE
		old_row := to_jsonb(OLD);
		new_row := to_jsonb(NEW);
	END IF;

	FOR column_name IN
		SELECT jsonb_object_keys(coalesce(new_row, old_row))
	LOOP
		-- `updated_at` and `updated_by` are bookkeeping, not a change (EARS-2).
		-- Since #516 EVERY `core` table carries both, written by
		-- `core.audit_columns_stamp()` below rather than by any caller. Naming
		-- either in a whitelist would grant a value that can never be written,
		-- and recording `updated_by` would ALSO break EARS-3: a touch by a
		-- different person changes that column and nothing else, so the ledger
		-- would gain a row for a change that never happened. The actor of the
		-- change is already this row's own `actor_email`.
		CONTINUE WHEN column_name IN ('updated_at', 'updated_by');

		old_value := old_row -> column_name;
		new_value := new_row -> column_name;

		-- An UPDATE records only what actually changed; a touch is not a change.
		CONTINUE WHEN TG_OP = 'UPDATE' AND old_value IS NOT DISTINCT FROM new_value;

		IF column_name = ANY (whitelist) THEN
			IF TG_OP = 'INSERT' THEN
				row_diff := row_diff || jsonb_build_object(column_name, jsonb_build_object('new', new_value));
			ELSIF TG_OP = 'DELETE' THEN
				row_diff := row_diff || jsonb_build_object(column_name, jsonb_build_object('old', old_value));
			ELSE
				row_diff := row_diff || jsonb_build_object(column_name, jsonb_build_object('old', old_value, 'new', new_value));
			END IF;
		ELSE
			-- Default-deny: the FACT of the change is in the ledger, the value
			-- never is — on INSERT, UPDATE and DELETE alike (EARS-2, EARS-27).
			row_diff := row_diff || jsonb_build_object(column_name, jsonb_build_object('changed', true));
		END IF;
	END LOOP;

	-- Nothing changed after those rules: write NO row. The trail records
	-- changes, not touches (EARS-3).
	IF TG_OP = 'UPDATE' AND row_diff = '{}'::jsonb THEN
		RETURN NULL;
	END IF;

	-- --- the primary key, from the catalog (EARS-4) -------------------------
	--
	-- Read from `pg_index`/`pg_attribute` on TG_RELID rather than from a
	-- per-table list, so a COMPOSITE primary key is carried with no per-table
	-- code — for tables that do not exist yet as much as for the six that do.
	SELECT jsonb_object_agg(att.attname, coalesce(new_row, old_row) -> att.attname)
	INTO pk_value
	FROM pg_index idx
	JOIN pg_attribute att
		ON att.attrelid = idx.indrelid
		AND att.attnum = ANY (idx.indkey)
	WHERE idx.indrelid = TG_RELID
		AND idx.indisprimary;

	INSERT INTO core.audit_event
		(event_type, table_name, actor_email, source, pk, diff, txid)
	VALUES (
		'data.' || TG_TABLE_NAME || '.' || lower(TG_OP),
		TG_TABLE_NAME,
		actor,
		src,
		coalesce(pk_value, '{}'::jsonb),
		row_diff,
		-- `pg_current_xact_id()`, not the wrapping 32-bit `txid_current()`: this
		-- column is a GROUPING key, so every row written by one save is grouped.
		pg_current_xact_id()::text
	);

	-- AFTER trigger: the return value is ignored, and NULL says so.
	RETURN NULL;
END;
$$;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 3. The stamping function
-- ---------------------------------------------------------------------------
--
-- Maintenance of the four columns is a DATABASE TRIGGER, not the write layer.
-- The alternative — every caller setting `updated_at` — was rejected because a
-- `cli:*` script, a fixture, a seed and a hand-run `psql` statement are all
-- legitimate writers here, and the one that forgets is exactly the one whose
-- row later reads as untouched. One trigger attributes all of them identically.
--
-- The ACTOR comes from the SAME session variable the journal reads —
-- `app.actor_email`, set by `platformTransaction()` — resolved to
-- `core.member.id`. So the row's `created_by` and the ledger's `actor_email`
-- cannot disagree about who wrote it. When the GUC is unset (an unmarked
-- connection: psql, the migration runner, a restore) or names an email no
-- member carries, the actor is NULL and the row still lands: refusing a
-- context-less write is already `core.audit_row_change()`'s job (EARS-26), and
-- a second refusal for one cause would only make the message worse.
--
-- `created_at` / `created_by` are IMMUTABLE: on UPDATE they are restored from
-- OLD, so an accidental `set created_by = …` cannot rewrite provenance.
--
-- On INSERT both are `coalesce(<what the caller wrote>, <the actor>)` rather
-- than the actor outright. `finance_intake_item.created_by` is the SUBMITTER —
-- for a backfilled request that is the person who filed it, not the operator
-- running the import — so overwriting an explicitly supplied value would lose
-- the fact the column exists to carry.
--
-- `SECURITY DEFINER` with a pinned `search_path`, like the capture function
-- beside it: this function reads `core.member`, and the pinned path is what
-- closes the search-path hijack `SECURITY DEFINER` otherwise opens.

CREATE OR REPLACE FUNCTION "core"."audit_columns_stamp"() RETURNS trigger
	LANGUAGE plpgsql
	SECURITY DEFINER
	SET search_path = pg_catalog, core
AS $$
DECLARE
	actor_id integer;
BEGIN
	SELECT m.id INTO actor_id
	FROM core.member m
	WHERE m.email = nullif(current_setting('app.actor_email', true), '');

	IF TG_OP = 'INSERT' THEN
		NEW.created_at := coalesce(NEW.created_at, now());
		NEW.created_by := coalesce(NEW.created_by, actor_id);
		NEW.updated_at := now();
		-- The session actor, never a copy of `created_by`. The two answer
		-- different questions: `created_by` is WHO THE ROW IS FOR where a caller
		-- supplied it (the submitter of a request filed on someone's behalf),
		-- while `updated_by` is WHO LAST WROTE IT. Copying the first into the
		-- second would name a person who never touched the row — the same
		-- fabrication the NULL-actor rule above refuses, arrived at from the
		-- other direction. A NULL here is the truthful answer for an unmarked
		-- connection, exactly as it is on the UPDATE arm.
		NEW.updated_by := actor_id;
	ELSE
		-- Immutable: whatever the statement said about these two, the row keeps
		-- what it was created with.
		NEW.created_at := OLD.created_at;
		NEW.created_by := OLD.created_by;
		NEW.updated_at := now();
		NEW.updated_by := actor_id;
	END IF;

	RETURN NEW;
END;
$$;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 4. The stamping triggers, one per table
-- ---------------------------------------------------------------------------
--
-- Literal per-table lines rather than a catalog loop: a `CREATE TRIGGER` hidden
-- inside a dynamic `format()` is invisible to `grep`, to review and to the
-- guards that read this chain as text. `core.audit_event` and
-- `core.__drizzle_migrations` are absent, and that absence is recorded with its
-- rationale in `tools/lint/audit-coverage-allowlist.mjs`
-- (`AUDIT_COLUMNS_EXEMPT_TABLES`).
--
-- BEFORE, so the stamped values are part of the row the AFTER capture trigger
-- then reads: one save produces one consistent pair of records.

CREATE OR REPLACE TRIGGER "finance_account_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_account"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_category_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_category"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_conversion_step_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_conversion_step"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_counterparty_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_counterparty"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_currency_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_currency"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_document_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_document"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_document_link_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_document_link"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_intake_item_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_intake_item"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_operation_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_operation"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_posting_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_posting"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_product_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_product"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_project_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_project"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_purpose_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_purpose"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_purpose_proposal_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."finance_purpose_proposal"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_assessment_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."hours_assessment"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_participant_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."hours_participant"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_period_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."hours_period"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_publication_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."hours_publication"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_publication_message_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."hours_publication_message"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "member_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."member"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

CREATE OR REPLACE TRIGGER "member_alias_audit_columns"
	BEFORE INSERT OR UPDATE ON "core"."member_alias"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_columns_stamp"();--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 5. The capture triggers, re-attached with the two immutable audit columns
-- ---------------------------------------------------------------------------
--
-- `created_at` and `created_by` are written once and never change, so they are
-- recorded BY VALUE (EARS-17): the INSERT event then carries the row's whole
-- provenance. Under default-deny (EARS-27) a column the trigger's arguments do
-- not name would record `{"changed": true}` and nothing else, so the arguments
-- have to grow — and the whole list is re-stated per table, because `TG_ARGV`
-- is replaced wholesale rather than appended to.
--
-- `updated_at` / `updated_by` are deliberately NOT here: section 2 drops both
-- from the diff entirely, so naming them would grant a value that can never be
-- written. Their absence is recorded as the `*.updated_at` / `*.updated_by`
-- exclusions in `tools/lint/audit-coverage-allowlist.mjs`.
--
-- The mirror `AUDIT_VALUE_WHITELIST` in that same file derives the pair rather
-- than repeating it 21 times, and the integration tier compares the mirror to
-- `pg_trigger.tgargs` exactly — so a table this section forgot is still caught.

CREATE OR REPLACE TRIGGER "finance_account_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_account"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'name', 'kind', 'currency', 'is_system', 'retired_at',
		'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_category_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_category"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'name', 'allocable', 'retired_at', 'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_conversion_step_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_conversion_step"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'operation_id', 'step_no', 'from_currency', 'to_currency', 'rate',
		'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_counterparty_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_counterparty"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'name', 'created_by', 'created_at'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_currency_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_currency"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'code', 'name', 'precision', 'retired_at', 'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_document_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_document"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'storage_key', 'content_digest', 'filename', 'mime', 'size',
		'kind', 'storage_state', 'uploaded_by', 'uploaded_at', 'created_at',
		'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_document_link_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_document_link"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'document_id', 'intake_item_id', 'linked_by', 'linked_at',
		'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_intake_item_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_intake_item"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'source', 'source_ref', 'kind', 'status', 'occurred_on',
		'account_id', 'counter_account_id', 'amount', 'currency', 'paid_amount',
		'paid_currency', 'fee_amount', 'fee_currency', 'purpose_id',
		'project_id', 'product_id', 'counterparty_id', 'member_id', 'note',
		'already_paid', 'personal_funds', 'created_by', 'decided_by',
		'decided_at', 'refusal_reason', 'posted_by', 'posted_at', 'operation_id',
		'created_at'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_operation_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_operation"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'occurred_on', 'purpose_id', 'source', 'source_ref', 'backdated',
		'reverses', 'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_posting_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_posting"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'operation_id', 'account_id', 'amount', 'currency', 'project_id',
		'category_id', 'product_id', 'member_id', 'conversion_step_id',
		'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_product_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_product"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'project_id', 'name', 'sale_price', 'sale_price_currency',
		'retired_at', 'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_project_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_project"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'name', 'is_fund', 'retired_at', 'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_purpose_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_purpose"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'name', 'category_id', 'product_binding', 'retired_at',
		'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "finance_purpose_proposal_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_purpose_proposal"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'intake_item_id', 'text', 'proposed_by', 'created_at',
		'resolved_purpose_id', 'resolved_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_assessment_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."hours_assessment"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'period_id', 'member_id', 'hours', 'method', 'weekend_hours',
		'split_percent', 'monthly_rate', 'hourly_rate', 'accrual', 'cash_amount',
		'invest_amount', 'weekday_count', 'saved_at', 'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_participant_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."hours_participant"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'member_id', 'fork_min', 'fork_max', 'grade', 'sort_key', 'created_at',
		'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_period_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."hours_period"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'label', 'date_from', 'date_to', 'status', 'sort_key',
		'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_publication_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."hours_publication"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'period_id', 'status', 'started_at', 'published_at',
		'preview_fingerprint', 'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "hours_publication_message_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."hours_publication_message"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'period_id', 'position', 'email', 'text', 'delivery', 'sent_at',
		'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "member_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."member"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'slug', 'email', 'name', 'role', 'status', 'timezone',
		'created_at', 'created_by'
	);--> statement-breakpoint

CREATE OR REPLACE TRIGGER "member_alias_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."member_alias"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'member_id', 'kind', 'created_at', 'created_by'
	);--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 6. The backfill, from the change journal
-- ---------------------------------------------------------------------------
--
-- Every row that predates this migration has `now()` in both timestamps and a
-- NULL actor — which would be a fabricated fact wherever the journal already
-- knows better. `core.audit_event` has held one row per write since `0003`, so
-- for a row it covers the answer is already recorded:
--
--   * `created_at` / `created_by` <- the row's OWN `data.<table>.insert` event
--     for that primary key (the most recent one — see the DESC note below);
--   * `updated_at` / `updated_by` <- the LATEST event of ANY type for it.
--
-- **What the journal may and may not touch.** The journal FILLS A GAP; it never
-- overwrites a value the row already carries. Four of these columns are new on
-- nineteen tables and were already there on three, and the difference is not
-- cosmetic: `finance_counterparty.created_by` and `finance_intake_item.created_by`
-- mean «the SUBMITTER», not «who executed the INSERT». For a request filed on
-- someone's behalf — which is the whole of the reconstructed population #517
-- describes — those are two different people, the journal holds the operator,
-- and the column holds the person the request is for. A backfill preferring the
-- journal would rewrite the requester with the importer, on a value the finance
-- board renders. So `created_by` and `updated_by` are
-- `coalesce(<the row's value>, <the journal's>)`: stored first, journal second.
-- No table carries a pre-existing `updated_by` today; the rule is written for
-- both columns anyway, because the next table to arrive with one must not
-- depend on this migration being re-read.
--
-- The two TIMESTAMPS cannot use the same shape, because they are NOT NULL with
-- a default: `r.created_at` is never null, so a plain `coalesce` in that order
-- would disable half the backfill outright. The honest question is «was this
-- column added by THIS migration?», and the answer is in the value itself: the
-- `ADD COLUMN … DEFAULT now()` block above stamps every pre-existing row with
-- `now()`, which inside one transaction is `transaction_timestamp()` — the same
-- instant this UPDATE reads. So `r.created_at = now()` is true exactly for a
-- column this migration created, and false for one that arrived with real data
-- earlier. Today that resolves to three exceptions preserved untouched:
-- `member.created_at`, `member.updated_at`, `finance_counterparty.created_at`
-- and `finance_purpose_proposal.created_at`. The issue's own acceptance line —
-- «existing per-table `created_at` / `updated_at` moved onto the helper WITHOUT
-- DATA LOSS» — is what this clause satisfies.
--
-- `actor_email` is mapped to `core.member.id`; an email no member carries (a
-- departed person, a `db-direct` write) yields NULL rather than a guess. A row
-- the journal does not cover keeps the `now()` default and a NULL actor — the
-- honest «we do not know», never the migration's own clock dressed as a fact.
-- The known consequence, stated in #516 itself: the 47 reconstructed requests
-- get their RECONSTRUCTION date, and #517 lifts the real filing date from the
-- note's `source_created_at` line on top of this.
--
-- **The primary key join is catalog-driven.** `audit_event.pk` is a jsonb
-- object keyed by the table's real PK columns (`0003` reads them from
-- `pg_index`), so a composite key and a text key (`finance_currency.code`) need
-- no per-table code here either: every PK column is compared as text against
-- `pk->>'<column>'`.
--
-- **User triggers are OFF for the backfill, and that is the whole point.** Left
-- on, this block would do two wrong things at once: the stamping trigger of
-- section 3 would overwrite every value being restored with `now()`, and the
-- capture trigger would append ~one `db-direct` UPDATE event per existing row —
-- flooding the very journal being read with entries recording nothing but this
-- migration. `ALTER TABLE … DISABLE TRIGGER USER` is the form used rather than
-- `session_replication_role = replica`: the latter needs superuser, and the
-- migration runs as `platform_migrator`, which merely OWNS these tables (#278).
-- Ownership is exactly what `DISABLE TRIGGER USER` requires.

DO $audit_columns_backfill$
DECLARE
	rec        record;
	pk_cols    text[];
	join_cond  text;
	first_ev   text;
	last_ev    text;
BEGIN
	FOR rec IN
		SELECT cls.oid, cls.relname AS table_name
		FROM pg_class cls
		JOIN pg_namespace nsp ON nsp.oid = cls.relnamespace
		WHERE nsp.nspname = 'core'
			AND cls.relkind = 'r'
			AND cls.relname NOT IN ('audit_event', '__drizzle_migrations')
		ORDER BY cls.relname
	LOOP
		SELECT array_agg(att.attname ORDER BY att.attnum)
		INTO pk_cols
		FROM pg_index idx
		JOIN pg_attribute att ON att.attrelid = idx.indrelid AND att.attnum = ANY (idx.indkey)
		WHERE idx.indrelid = rec.oid AND idx.indisprimary;

		-- A table with no primary key cannot be joined to the journal at all;
		-- its rows keep the default rather than being matched by guesswork.
		CONTINUE WHEN pk_cols IS NULL;

		SELECT string_agg(format('ev.pk->>%L is not distinct from (r.%I)::text', col, col), ' and ')
		INTO join_cond
		FROM unnest(pk_cols) AS col;

		first_ev := format(
			'select ev.created_at as at, (select m.id from core.member m where m.email = ev.actor_email) as actor'
			|| ' from core.audit_event ev where ev.table_name = %L and ev.event_type = %L and %s'
			-- DESC, i.e. the row's OWN insert rather than the oldest one ever
			-- recorded under that key. A primary key is reused after
			-- `TRUNCATE … RESTART IDENTITY`, which the integration tier and the
			-- dev seed both do, so the oldest insert event under key 7 can belong
			-- to a row that no longer exists. For a key that was inserted once —
			-- production, and every row this backfill actually cares about — the
			-- two orderings name the same event.
			|| ' order by ev.id desc limit 1',
			rec.table_name, 'data.' || rec.table_name || '.insert', join_cond);

		last_ev := format(
			'select ev.created_at as at, (select m.id from core.member m where m.email = ev.actor_email) as actor'
			|| ' from core.audit_event ev where ev.table_name = %L and %s'
			|| ' order by ev.id desc limit 1',
			rec.table_name, join_cond);

		EXECUTE format('ALTER TABLE core.%I DISABLE TRIGGER USER', rec.table_name);

		-- PRECEDENCE: a value the ROW already carries always wins; the journal
		-- only ever fills a gap. See the «What the journal may and may not
		-- touch» note above for why the two actor columns and the two
		-- timestamps need different shapes of the same rule.
		EXECUTE format(
			'UPDATE core.%1$I AS r SET'
			|| ' created_at = CASE WHEN r.created_at = now()'
			|| '                   THEN coalesce((select at from (%2$s) f), r.created_at)'
			|| '                   ELSE r.created_at END,'
			|| ' created_by = coalesce(r.created_by, (select actor from (%2$s) f)),'
			|| ' updated_at = CASE WHEN r.updated_at = now()'
			|| '                   THEN coalesce((select at from (%3$s) l), r.updated_at)'
			|| '                   ELSE r.updated_at END,'
			|| ' updated_by = coalesce(r.updated_by, (select actor from (%3$s) l))',
			rec.table_name, first_ev, last_ev);

		EXECUTE format('ALTER TABLE core.%I ENABLE TRIGGER USER', rec.table_name);
	END LOOP;
END
$audit_columns_backfill$;
