-- `core.finance_intake_item.provenance`, and the note the reconstruction
-- overwrote (issue #517; owner go, Антон, 2026-09-22; spec 339 §B EARS-503
-- revised, EARS-535/536/537).
--
-- THE RULE: `note` is HUMAN TEXT, `provenance` is WHAT THE SOURCE SAID, and
-- `source_ref` is WHERE IT WAS SAID. Three different questions, three places.
--
-- WHY, in the order it happened. The 47 expense requests reconstructed from the
-- «BBM Финансы» Mattermost channel had nowhere to record their origin: EARS-503
-- FORBADE `source_ref` on a `request`, and no structured column existed. So the
-- reconstruction wrote `source_system=mattermost`, `source_post_id=…`,
-- `source_created_at=…`, `source_item=…` and some eighty other keys as plain
-- `key=value` lines into `note` — the column `RequestDetailsSheet.tsx` renders
-- as one appended paragraph. The owner read the result and said provenance was
-- «просто заметка в комментарии» (Антон, 2026-09-22). The submission moment had
-- the same fate: `created_at` did not exist until `0016`, and the backfill there
-- can only give these rows the date the RECONSTRUCTION ran — the real filing
-- moment survives nowhere but that `source_created_at=` line.
--
-- Order below: the generated column + constraint swap -> the capture trigger
-- re-attached with the new column -> the repair, with user triggers off.
--
-- The first three statements are GENERATED by drizzle-kit (so the snapshot
-- under `meta/` knows the column and the constraint); everything after them is
-- HAND-WRITTEN, because drizzle-orm 0.45 can express neither a trigger nor a
-- data repair — the shape `0003_universal_edit_audit.sql` established here and
-- `0016_audit_columns.sql` last used.

ALTER TABLE "core"."finance_intake_item" DROP CONSTRAINT "finance_intake_item_source_ref_policy";--> statement-breakpoint
ALTER TABLE "core"."finance_intake_item" ADD COLUMN "provenance" jsonb;--> statement-breakpoint
ALTER TABLE "core"."finance_intake_item" ADD CONSTRAINT "finance_intake_item_source_ref_policy" CHECK (("core"."finance_intake_item"."source" not in ('bank_import', 'backfill')) or ("core"."finance_intake_item"."source_ref" is not null));--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 1. The capture trigger, re-attached with `provenance` in its whitelist
-- ---------------------------------------------------------------------------
--
-- `core.audit_row_change()` records ONLY the columns its trigger arguments
-- name, and a column added later starts OUTSIDE that whitelist by design (spec
-- 201 EARS-27). `provenance` belongs inside it: it is the row's origin, it is
-- the one thing #517 declares immutable after submit (EARS-536), and a silent
-- rewrite of it is exactly the class of change the journal exists to make
-- visible. Nothing in it is a person's contact data — the class EARS-17 keeps
-- out — because it holds what a Mattermost post said about an expense.
--
-- Re-emitted whole rather than patched: `CREATE OR REPLACE TRIGGER` takes the
-- full argument list, and the list is the whitelist. The only difference from
-- `0016_audit_columns.sql` §5 is the final `'provenance'`.

CREATE OR REPLACE TRIGGER "finance_intake_item_audit"
	AFTER INSERT OR UPDATE OR DELETE ON "core"."finance_intake_item"
	FOR EACH ROW EXECUTE FUNCTION "core"."audit_row_change"(
		'id', 'source', 'source_ref', 'kind', 'status', 'occurred_on',
		'account_id', 'counter_account_id', 'amount', 'currency', 'paid_amount',
		'paid_currency', 'fee_amount', 'fee_currency', 'purpose_id',
		'project_id', 'product_id', 'counterparty_id', 'member_id', 'note',
		'already_paid', 'personal_funds', 'created_by', 'decided_by',
		'decided_at', 'refusal_reason', 'posted_by', 'posted_at', 'operation_id',
		'created_at', 'provenance'
	);--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 2. The repair: the `key=value` block leaves `note`
-- ---------------------------------------------------------------------------
--
-- **What it selects, and why that predicate.** A row is repaired exactly when
-- its `note` carries a line `source_system=…` at the start of a line. Not «any
-- note with an equals sign in it» — a human writing «итого=12000» in a comment
-- is not provenance, and a repair that guessed would eat their sentence. The
-- predicate is also what makes the block IDEMPOTENT and SAFE TO RE-RUN: after
-- the first pass no row has such a line left, so a second run updates nothing,
-- and on a database where the reconstruction never happened (a fresh stand, CI)
-- it is a no-op from the first statement.
--
-- **What it writes.**
--
--   * `provenance` <- every `^[a-z_]+=` line of the note, as a flat jsonb
--     object of STRINGS. An empty value stays `""` rather than becoming null:
--     `source_item=` recorded in the corpus means «this key applies and is
--     blank», and a null would erase the difference between that and a key that
--     was never written. `source_system` is written EXPLICITLY on top of the
--     parse, so the one key the resolver dispatches on (`sourceRefToUrl`) is a
--     fact of this migration rather than of the corpus's spelling.
--   * `note` <- the lines that are NOT `key=value`, in their original order,
--     trimmed; NULL when nothing human is left. That is the whole point: the
--     details sheet renders `note`, and it must render a sentence again.
--   * `source_ref` <- `source_post_id`, or `<source_post_id>#<source_item>` for
--     the ten rows where ONE Mattermost post was split into several intake
--     items. The `#` suffix is what keeps EARS-504's partial unique index
--     `(source, source_ref)` true across those splits; without it the five rows
--     of post `dhyq4p4yepgwzy9qk5p5iw65uc` would collide. A row with no post id
--     keeps a NULL ref, which the revised EARS-503 policy above now allows for
--     `request`.
--   * `created_at` <- `source_created_at`, the ISO-Z instant the Mattermost post
--     was written. Verified 47/47 against `posts.createat` on the live
--     Mattermost (only millisecond precision differs — the note was recorded to
--     the second). Guarded by a regexp so a malformed value leaves the column
--     alone rather than aborting the migration.
--
-- **User triggers are OFF, and for two independent reasons.** `created_at` is
-- IMMUTABLE: `core.audit_columns_stamp()` restores it from OLD on every UPDATE
-- (`0016` §3), so with the trigger on, the one column this task exists to fix
-- would silently keep the reconstruction date. And the capture trigger would
-- append one `db-direct` UPDATE event per repaired row, recording nothing but
-- this migration. `ALTER TABLE … DISABLE TRIGGER USER` rather than
-- `session_replication_role = replica` for the reason `0016` §6 gives: the
-- latter needs superuser, and the migration runs as `platform_migrator`, which
-- merely OWNS the table. Ownership is what `DISABLE TRIGGER USER` requires.
--
-- **`updated_at` / `updated_by` are deliberately NOT touched.** They answer
-- «when was this row last written», and this migration IS a write of it — but
-- with the stamping trigger off there is nothing to bump them to except a
-- hand-written `now()`, which would claim the repair as an edit by nobody. The
-- row's last real edit is the truer answer, and the fact that a migration
-- rewrote these four columns is recorded here, in the migration.

DO $intake_provenance_repair$
DECLARE
	repaired integer;
BEGIN
	ALTER TABLE core.finance_intake_item DISABLE TRIGGER USER;

	WITH candidate AS (
		SELECT
			item.id,
			-- CRLF is normalised away first: a note that arrived through a
			-- Windows clipboard would otherwise leave `\r` glued to every value.
			replace(item.note, chr(13), '') AS text
		FROM core.finance_intake_item AS item
		WHERE item.note ~ '(^|\n)source_system='
	), split AS (
		SELECT candidate.id, line.ordinality AS position, line.value AS value
		FROM candidate,
			LATERAL unnest(string_to_array(candidate.text, chr(10)))
				WITH ORDINALITY AS line(value, ordinality)
	), parsed AS (
		SELECT
			split.id,
			coalesce(
				jsonb_object_agg(
					split_part(split.value, '=', 1),
					btrim(substring(split.value FROM position('=' IN split.value) + 1))
				) FILTER (WHERE split.value ~ '^[a-z_]+='),
				'{}'::jsonb
			) AS block,
			btrim(
				coalesce(
					string_agg(split.value, chr(10) ORDER BY split.position)
						FILTER (WHERE split.value !~ '^[a-z_]+='),
					''
				)
			) AS human
		FROM split
		GROUP BY split.id
	)
	UPDATE core.finance_intake_item AS item
	SET
		provenance = parsed.block || jsonb_build_object('source_system', 'mattermost'),
		note = nullif(parsed.human, ''),
		source_ref = CASE
			WHEN coalesce(parsed.block ->> 'source_post_id', '') = '' THEN item.source_ref
			WHEN coalesce(parsed.block ->> 'source_item', '') = '' THEN parsed.block ->> 'source_post_id'
			ELSE (parsed.block ->> 'source_post_id') || '#' || (parsed.block ->> 'source_item')
		END,
		created_at = CASE
			WHEN coalesce(parsed.block ->> 'source_created_at', '') ~ '^\d{4}-\d{2}-\d{2}'
				THEN (parsed.block ->> 'source_created_at')::timestamptz
			ELSE item.created_at
		END
	FROM parsed
	WHERE parsed.id = item.id;

	GET DIAGNOSTICS repaired = ROW_COUNT;
	RAISE NOTICE 'finance_intake_item: provenance lifted out of note on % row(s)', repaired;

	ALTER TABLE core.finance_intake_item ENABLE TRIGGER USER;
END
$intake_provenance_repair$;
